Repository mohitahlawat2001/box-office-react, pull requests merged in 2023-10, with the labels that each got.

#12 UI Update: Fix cards Ui and read more button UI, fixed search button text,
  src/components/SearchForm.jsx
  src/components/common/SearchCard.jsx
  src/components/shows/ShowCard.jsx
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#19 added pikachu running loader effect
  src/components/loader/Loader.jsx
  src/components/loader/pikachu.gif
  src/pages/Show.jsx
Labels: hacktoberfest, hacktoberfest-accepted

#20 Added the Readme.
  README.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted
